language: go
go:
  - "1.11.x"
  - "1.12.x"
  - "tip"

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10

script:
  - $GOPATH/bin/golangci-lint run
  - go test -v ./...
